name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-current:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Build test pages site
        run: npm install & npm run build
      
      - name: Copy Static Pages
        run: |
          mkdir -p public
          cp root/page1.html public/
          cp root/page2.html public/
          # cp root/index.html public/
          

      # - name: Upload artifacts or GitHub Pages
      #   uses: actions/upload-pages-artifact@v3
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for QA Approval
        uses: actions/github-script@v7
        # with:
        #   script: |
        # core.setOutput('approved', 'false')
        id: approval

  depoloy-qa:
    needs: deploy-current
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    # environment:
    #   name: QA
    #   # url: https://your-qa-url.example.com
    #   deployment_branch_policy:
    #     protected_branches: true
    steps:
      - name: QA Stage
        run: echo "QA stage running after deploy and approval."